import type { Group } from '../utility-classes.types';
import type { ClassExample } from './class-examples.types';

export const EXAMPLES: Record<Group, ClassExample[]> = {
  bg: [
    { cls: 'mat-bg-primary', use: 'The one main action on a screen.', html: `<button class="mat-bg-primary mat-text-on-primary mat-font-label-lg mat-corner-full">Pay now</button>` },
    { cls: 'mat-bg-primary-container', use: 'A friendly notice that is not an error.', html: `<div class="mat-bg-primary-container mat-text-on-primary-container mat-font-body-md mat-corner-md">Your trial ends in 3 days.</div>` },
    { cls: 'mat-bg-secondary', use: 'A strong marker that is not an action, like the current step.', html: `<span class="mat-bg-secondary mat-text-on-secondary mat-font-label-md mat-corner-full">Step 2 of 4</span>` },
    { cls: 'mat-bg-secondary-container', use: 'A selected filter chip or a selected list row.', html: `<span class="mat-bg-secondary-container mat-text-on-secondary-container mat-font-label-lg mat-corner-sm">✓ Unread</span>` },
    { cls: 'mat-bg-error', use: 'A count or dot that needs attention.', html: `<span class="mat-bg-error mat-text-on-error mat-font-label-sm mat-corner-full">3</span>` },
    { cls: 'mat-bg-error-container', use: 'A box that says something failed.', html: `<div class="mat-bg-error-container mat-text-on-error-container mat-font-body-md mat-corner-sm">Payment failed. Check your card details.</div>` },
    { cls: 'mat-bg-surface', use: 'The page itself, or a plain panel on it.', html: `<div class="mat-bg-surface mat-text-on-surface mat-font-body-md mat-border-subtle mat-corner-md">Account settings</div>` },
    { cls: 'mat-bg-surface-variant', use: 'A search box or a track that sits a little apart.', html: `<div class="mat-bg-surface-variant mat-text-on-surface-variant mat-font-body-lg mat-corner-full">Search orders</div>` },
    { cls: 'mat-bg-surface-container-lowest', use: 'The lightest box, such as a text area inside a card.', html: `<div class="mat-bg-surface-container-lowest mat-text-on-surface-variant mat-font-body-md mat-border-subtle mat-corner-sm">Add a note...</div>` },
    { cls: 'mat-bg-surface-container-low', use: 'A calm card or a bottom sheet.', html: `<div class="mat-bg-surface-container-low mat-text-on-surface mat-font-body-md mat-corner-lg mat-shadow-1">Order 4821, 3 items</div>` },
    { cls: 'mat-bg-surface-container', use: 'A menu or a side panel.', html: `<ul class="mat-bg-surface-container mat-text-on-surface mat-font-body-lg mat-corner-xs mat-shadow-2"><li>Rename</li><li>Duplicate</li><li>Delete</li></ul>` },
    { cls: 'mat-bg-surface-container-high', use: 'A panel that floats above the page, like a date picker.', html: `<div class="mat-bg-surface-container-high mat-text-on-surface mat-font-title-sm mat-corner-lg">September 2026</div>` },
    { cls: 'mat-bg-surface-container-highest', use: 'A filled card that should stand out most.', html: `<div class="mat-bg-surface-container-highest mat-text-on-surface mat-font-body-md mat-corner-md">Storage: 42 GB of 100 GB used</div>` },
    { cls: 'mat-bg-inverse-surface', use: 'A short notice that flips the colors, like a snackbar.', html: `<div class="mat-bg-inverse-surface mat-text-inverse-on-surface mat-font-body-md mat-corner-xs mat-shadow-3">Message archived</div>` },
    { cls: 'mat-bg-disabled', use: 'A filled button that cannot be used yet.', html: `<button disabled class="mat-bg-disabled mat-text-disabled mat-font-label-lg mat-corner-full">Submit</button>` },
  ],
  text: [
    { cls: 'mat-text-on-surface', use: 'Normal reading text on the page or a card.', html: `<p class="mat-text-on-surface mat-font-body-md">Your order ships tomorrow.</p>` },
    { cls: 'mat-text-on-surface-variant', use: 'Quieter text: captions, hints, timestamps.', html: `<p class="mat-text-on-surface-variant mat-font-body-sm">Updated 4 minutes ago</p>` },
    { cls: 'mat-text-primary', use: 'Text that should be noticed, such as a link.', html: `<a class="mat-text-primary mat-font-label-lg" href="#">View details</a>` },
    { cls: 'mat-text-secondary', use: 'A status word that is less loud than primary.', html: `<p class="mat-text-secondary mat-font-label-lg">Draft</p>` },
    { cls: 'mat-text-error', use: 'A validation message under a field.', html: `<p class="mat-text-error mat-font-body-sm">Email is required</p>` },
    { cls: 'mat-text-disabled', use: 'An option you cannot pick right now.', html: `<p class="mat-text-disabled mat-font-body-lg">Express delivery (unavailable)</p>` },
    { cls: 'mat-text-on-primary', use: 'Text on a mat-bg-primary fill.', html: `<span class="mat-bg-primary mat-text-on-primary mat-font-label-lg mat-corner-full">Checkout</span>` },
    { cls: 'mat-text-on-primary-container', use: 'Text on a mat-bg-primary-container fill.', html: `<div class="mat-bg-primary-container mat-text-on-primary-container mat-font-body-md mat-corner-sm">Tip: press / to search</div>` },
    { cls: 'mat-text-on-secondary', use: 'Text on a mat-bg-secondary fill.', html: `<span class="mat-bg-secondary mat-text-on-secondary mat-font-label-md mat-corner-full">Beta</span>` },
    { cls: 'mat-text-on-secondary-container', use: 'Text on a mat-bg-secondary-container fill.', html: `<span class="mat-bg-secondary-container mat-text-on-secondary-container mat-font-label-lg mat-corner-full">4 files selected</span>` },
    { cls: 'mat-text-on-error', use: 'Text on a mat-bg-error fill.', html: `<span class="mat-bg-error mat-text-on-error mat-font-label-md mat-corner-full">Offline</span>` },
    { cls: 'mat-text-on-error-container', use: 'Text on a mat-bg-error-container fill.', html: `<div class="mat-bg-error-container mat-text-on-error-container mat-font-body-md mat-corner-sm">2 fields need attention</div>` },
    { cls: 'mat-text-inverse-on-surface', use: 'Text on a mat-bg-inverse-surface fill.', html: `<div class="mat-bg-inverse-surface mat-text-inverse-on-surface mat-font-body-sm mat-corner-xs">Copied to clipboard</div>` },
  ],
  font: [
    { cls: 'mat-font-display-lg', use: 'One big number on a dashboard.', html: `<p class="mat-font-display-lg">$4,280</p>` },
    { cls: 'mat-font-display-md', use: 'A hero number or a very short hero word.', html: `<p class="mat-font-display-md">72°</p>` },
    { cls: 'mat-font-display-sm', use: 'A date or short headline in a hero area.', html: `<p class="mat-font-display-sm">29 Sep</p>` },
    { cls: 'mat-font-headline-lg', use: 'The page title on a large screen.', html: `<h1 class="mat-font-headline-lg">Reports</h1>` },
    { cls: 'mat-font-headline-md', use: 'A section title.', html: `<h2 class="mat-font-headline-md">Billing</h2>` },
    { cls: 'mat-font-headline-sm', use: 'A dialog title.', html: `<h2 class="mat-font-headline-sm">Delete this file?</h2>` },
    { cls: 'mat-font-title-lg', use: 'A card or toolbar title.', html: `<h3 class="mat-font-title-lg">Team members</h3>` },
    { cls: 'mat-font-title-md', use: 'The main line of a list item.', html: `<p class="mat-font-title-md">Sara Ali</p>` },
    { cls: 'mat-font-title-sm', use: 'A table column header.', html: `<p class="mat-font-title-sm">Invoice date</p>` },
    { cls: 'mat-font-body-lg', use: 'An intro paragraph.', html: `<p class="mat-font-body-lg">Pick a plan to get started. You can change it any time.</p>` },
    { cls: 'mat-font-body-md', use: 'Default body text, table rows, dialog text.', html: `<p class="mat-font-body-md">We sent a code to your email. It expires in 10 minutes.</p>` },
    { cls: 'mat-font-body-sm', use: 'Captions and hints under fields.', html: `<p class="mat-font-body-sm mat-text-on-surface-variant">Must be at least 8 characters</p>` },
    { cls: 'mat-font-label-lg', use: 'Button and menu labels.', html: `<button class="mat-font-label-lg mat-border mat-corner-full mat-text-primary">Save draft</button>` },
    { cls: 'mat-font-label-md', use: 'A slider value or a small tag.', html: `<span class="mat-font-label-md mat-bg-secondary-container mat-text-on-secondary-container mat-corner-sm">45%</span>` },
    { cls: 'mat-font-label-sm', use: 'Text inside a badge.', html: `<span class="mat-font-label-sm mat-bg-error mat-text-on-error mat-corner-full">NEW</span>` },
  ],
  corner: [
    { cls: 'mat-corner-xs', use: 'Small, short-lived things: tooltips, snackbars. 4px.', html: `<span class="mat-corner-xs mat-bg-inverse-surface mat-text-inverse-on-surface mat-font-body-sm">Copy link</span>` },
    { cls: 'mat-corner-sm', use: 'Text fields and small chips. 8px.', html: `<div class="mat-corner-sm mat-border mat-font-body-lg mat-text-on-surface-variant">Email address</div>` },
    { cls: 'mat-corner-md', use: 'Cards. 12px.', html: `<div class="mat-corner-md mat-bg-surface-container-highest mat-font-body-md">Weekly summary: 12 new orders</div>` },
    { cls: 'mat-corner-lg', use: 'FABs and the date picker. 16px.', html: `<button class="mat-corner-lg mat-bg-primary-container mat-text-on-primary-container mat-shadow-3 mat-font-label-lg">+ New</button>` },
    { cls: 'mat-corner-xl', use: 'Dialogs and large sheets. 28px.', html: `<div class="mat-corner-xl mat-bg-surface-container-high mat-font-body-md mat-shadow-3">Discard your changes?</div>` },
    { cls: 'mat-corner-full', use: 'Pills: buttons, badges, avatars.', html: `<span class="mat-corner-full mat-bg-primary mat-text-on-primary mat-font-title-sm">SA</span>` },
  ],
  'border-shadow': [
    { cls: 'mat-border', use: 'An edge you should clearly see: outlined buttons and inputs.', html: `<button class="mat-border mat-corner-full mat-text-primary mat-font-label-lg">Cancel</button>` },
    { cls: 'mat-border-subtle', use: 'A quiet edge: outlined cards and dividers.', html: `<div class="mat-border-subtle mat-corner-md mat-font-body-md">Shipping address<br>12 King Street, London</div>` },
    { cls: 'mat-shadow-1', use: 'Slightly raised: an elevated card.', html: `<div class="mat-shadow-1 mat-bg-surface-container-low mat-corner-md mat-font-body-md">Elevated card</div>` },
    { cls: 'mat-shadow-2', use: 'Raised: menus and select panels.', html: `<div class="mat-shadow-2 mat-bg-surface-container mat-corner-xs mat-font-body-lg">Sort by date</div>` },
    { cls: 'mat-shadow-3', use: 'A FAB, or a dialog above the page.', html: `<button class="mat-shadow-3 mat-bg-primary-container mat-text-on-primary-container mat-corner-lg mat-font-label-lg">+ Compose</button>` },
    { cls: 'mat-shadow-4', use: 'Hover and focus lift, such as a hovered FAB.', html: `<button class="mat-shadow-4 mat-bg-primary-container mat-text-on-primary-container mat-corner-lg mat-font-label-lg">+ Compose (hover)</button>` },
    { cls: 'mat-shadow-5', use: 'The highest lift, such as a card being dragged.', html: `<div class="mat-shadow-5 mat-bg-surface-container-low mat-corner-md mat-font-body-md">Dragging: Invoice 2041</div>` },
  ],
};
