import type { Message } from './list-detail.types';

export const MESSAGES: Message[] = [
  {
    id: 1,
    from: 'Dana Whitfield',
    subject: 'Chair arrived damaged',
    preview: 'The box was crushed on one corner and the armrest...',
    body: 'The box was crushed on one corner and the armrest is cracked. I have photos if that helps. Can you send a replacement rather than a refund? I still want the chair.',
    time: '09:12',
    unread: true,
    label: 'Support',
  },
  {
    id: 2,
    from: 'Ivo Marek',
    subject: 'Invoice #4788 has the wrong VAT',
    preview: 'We are registered in Czechia so this should be...',
    body: 'We are registered in Czechia so this should be reverse charged. Our VAT number is CZ12345678. Could you reissue the invoice with that applied?',
    time: '08:40',
    unread: true,
    label: 'Billing',
  },
  {
    id: 3,
    from: 'Lena Osei',
    subject: 'Bulk order for 24 desks',
    preview: 'We are fitting out a new floor in November and...',
    body: 'We are fitting out a new floor in November and need 24 standing desks delivered in one shipment. What does the lead time look like, and is there a volume discount at that quantity?',
    time: 'Yesterday',
    unread: false,
    label: 'Sales',
  },
  {
    id: 4,
    from: 'Pris Ramos',
    subject: 'Cannot reset my password',
    preview: 'The reset email never arrives. I have checked spam...',
    body: 'The reset email never arrives. I have checked spam and the address is right. It is the same one I am writing from now.',
    time: 'Yesterday',
    unread: false,
    label: 'Support',
  },
  {
    id: 5,
    from: 'Tomas Berg',
    subject: 'Renewal quote for 2027',
    preview: 'Our contract ends in January. Could you send...',
    body: 'Our contract ends in January. Could you send a renewal quote with the same seat count, and one with 40 seats so I can take both to finance?',
    time: 'Mon',
    unread: false,
    label: 'Sales',
  },
];
